In [1]:
import pandas as pd

with open('sat.trn') as f:
    data = f.readlines()

training_data =pd.DataFrame([list(map(int, line.split())) for line in data])

training_data

# training_data.columns = ['a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y',
#                           'z','aa','ab','ac','ad','ae','af','ag','ah','ai','aj','ak']

,0,1,2,3,4,5,6,7,8,9,...,27,28,29,30,31,32,33,34,35,36
0,92,115,120,94,84,102,106,79,84,102,...,104,88,121,128,100,84,107,113,87,3
1,84,102,106,79,84,102,102,83,80,102,...,100,84,107,113,87,84,99,104,79,3
2,84,102,102,83,80,102,102,79,84,94,...,87,84,99,104,79,84,99,104,79,3
3,80,102,102,79,84,94,102,79,80,94,...,79,84,99,104,79,84,103,104,79,3
4,84,94,102,79,80,94,98,76,80,102,...,79,84,103,104,79,79,107,109,87,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4430,56,64,108,96,64,71,108,96,68,75,...,92,66,83,108,96,66,87,104,89,5
4431,64,71,108,96,68,75,108,96,71,87,...,96,66,87,104,89,63,87,104,89,5
4432,68,75,108,96,71,87,108,88,71,91,...,89,63,87,104,89,70,100,104,85,4
4433,71,87,108,88,71,91,100,81,76,95,...,89,70,100,104,85,70,91,104,85,4
4434,71,91,100,81,76,95,108,88,80,95,...,85,70,91,104,85,63,91,100,81,4

In [2]:
with open('sat.tst') as f:
    data = f.readlines()

test_data =pd.DataFrame([list(map(int, line.split())) for line in data])

test_data

# test_data.columns = ['a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z',
#                'aa','ab','ac','ad','ae','af','ag','ah','ai','aj','ak']

,0,1,2,3,4,5,6,7,8,9,...,27,28,29,30,31,32,33,34,35,36
0,80,102,102,79,76,102,102,79,76,102,...,87,79,107,109,87,79,107,113,87,3
1,76,102,102,79,76,102,106,83,76,102,...,87,79,107,113,87,79,103,104,83,3
2,80,98,106,79,76,94,102,76,76,94,...,79,79,95,100,79,79,95,96,75,4
3,76,94,102,76,76,94,102,76,76,94,...,79,79,95,96,75,79,95,100,75,4
4,76,94,102,76,76,94,102,76,76,89,...,75,79,95,100,75,75,95,100,79,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,60,83,96,85,64,87,100,88,64,83,...,92,66,87,108,89,63,83,104,85,1
1996,64,79,100,85,56,71,96,85,56,68,...,85,66,83,100,85,63,83,100,81,1
1997,56,68,91,81,56,64,91,81,53,64,...,81,59,87,96,81,63,83,92,74,5
1998,56,68,87,74,60,71,91,81,60,64,...,74,59,83,92,74,59,83,92,70,5
1999,60,71,91,81,60,64,104,99,56,64,...,74,59,83,92,70,63,79,108,92,5

In [3]:
merge_data = pd.concat([training_data, test_data], axis= 0)

merge_data.columns = ['a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z',
               'aa','ab','ac','ad','ae','af','ag','ah','ai','aj','class']

merge_data

,a,b,c,d,e,f,g,h,i,j,...,ab,ac,ad,ae,af,ag,ah,ai,aj,class
0,92,115,120,94,84,102,106,79,84,102,...,104,88,121,128,100,84,107,113,87,3
1,84,102,106,79,84,102,102,83,80,102,...,100,84,107,113,87,84,99,104,79,3
2,84,102,102,83,80,102,102,79,84,94,...,87,84,99,104,79,84,99,104,79,3
3,80,102,102,79,84,94,102,79,80,94,...,79,84,99,104,79,84,103,104,79,3
4,84,94,102,79,80,94,98,76,80,102,...,79,84,103,104,79,79,107,109,87,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,60,83,96,85,64,87,100,88,64,83,...,92,66,87,108,89,63,83,104,85,1
1996,64,79,100,85,56,71,96,85,56,68,...,85,66,83,100,85,63,83,100,81,1
1997,56,68,91,81,56,64,91,81,53,64,...,81,59,87,96,81,63,83,92,74,5
1998,56,68,87,74,60,71,91,81,60,64,...,74,59,83,92,74,59,83,92,70,5
1999,60,71,91,81,60,64,104,99,56,64,...,74,59,83,92,70,63,79,108,92,5

In [4]:
x = merge_data.iloc[:, :-1]
x

,a,b,c,d,e,f,g,h,i,j,...,aa,ab,ac,ad,ae,af,ag,ah,ai,aj
0,92,115,120,94,84,102,106,79,84,102,...,134,104,88,121,128,100,84,107,113,87
1,84,102,106,79,84,102,102,83,80,102,...,128,100,84,107,113,87,84,99,104,79
2,84,102,102,83,80,102,102,79,84,94,...,113,87,84,99,104,79,84,99,104,79
3,80,102,102,79,84,94,102,79,80,94,...,104,79,84,99,104,79,84,103,104,79
4,84,94,102,79,80,94,98,76,80,102,...,104,79,84,103,104,79,79,107,109,87
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,60,83,96,85,64,87,100,88,64,83,...,104,92,66,87,108,89,63,83,104,85
1996,64,79,100,85,56,71,96,85,56,68,...,100,85,66,83,100,85,63,83,100,81
1997,56,68,91,81,56,64,91,81,53,64,...,100,81,59,87,96,81,63,83,92,74
1998,56,68,87,74,60,71,91,81,60,64,...,96,74,59,83,92,74,59,83,92,70
1999,60,71,91,81,60,64,104,99,56,64,...,92,74,59,83,92,70,63,79,108,92

In [5]:
y = merge_data.iloc[:,-1]
y

0       3
1       3
2       3
3       3
4       3
       ..
1995    1
1996    1
1997    5
1998    5
1999    5
Name: class, Length: 6435, dtype: int64

## split the dataset in train  &  test set

In [6]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size= 0.2, random_state= 22)

# Normalize the data using any normalization technique

In [7]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

In [8]:
x_train = scaler.fit_transform(x_train)

x_test = scaler.transform(x_test)

# SVC  classification

In [9]:
from sklearn.svm import SVC

In [10]:
classification = SVC(kernel= 'linear', random_state= 0)

classification.fit(x_train, y_train)

SVC(kernel='linear', random_state=0)

In [11]:
y_pred = classification.predict(x_test)

In [12]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [13]:
metrix = confusion_matrix(y_test, y_pred)
metrix

array([[295,   0,   1,   1,   2,   0],
       [  0, 134,   0,   0,   4,   0],
       [  1,   0, 281,   9,   0,   0],
       [  0,   0,  25,  51,   2,  37],
       [  6,   9,   0,   2, 109,  19],
       [  0,   0,   6,  30,   8, 255]], dtype=int64)

In [14]:
score = accuracy_score(y_test, y_pred)
score

0.8741258741258742

# Hyper parameter tuning

In [15]:
from sklearn.model_selection import GridSearchCV

In [16]:
parameters = [{'C' : [0.1,0.6,1,10], 'kernel' : ['linear']},
             
             {'C': [1,5,10,12], 'kernel': ['rbf'], 'gamma':[0.01,0.05,0.1,0.2,0.3]}]

In [17]:
grid_search = GridSearchCV(estimator= classification, param_grid= parameters, scoring= 'accuracy', cv = 10, n_jobs= -1)

grid_search.fit(x_train, y_train)

GridSearchCV(cv=10, estimator=SVC(kernel='linear', random_state=0), n_jobs=-1,
             param_grid=[{'C': [0.1, 0.6, 1, 10], 'kernel': ['linear']},
                         {'C': [1, 5, 10, 12],
                          'gamma': [0.01, 0.05, 0.1, 0.2, 0.3],
                          'kernel': ['rbf']}],
             scoring='accuracy')

In [18]:
accuracy = grid_search.best_score_

accuracy

0.92696006951003

In [19]:
grid_search.best_params_

{'C': 5, 'gamma': 0.2, 'kernel': 'rbf'}

### apply the best outcome parameters in SVC

In [20]:
from sklearn.svm import SVC

classification = SVC(C = 5, kernel= 'rbf', gamma= 0.2)

In [21]:
classification.fit(x_train, y_train)

SVC(C=5, gamma=0.2)

In [22]:
y_pred2 = classification.predict(x_test)

In [23]:
cm = confusion_matrix(y_pred2, y_test)

cm

array([[296,   0,   2,   0,   1,   0],
       [  0, 136,   0,   0,   2,   0],
       [  1,   1, 279,  20,   0,  10],
       [  0,   0,   5,  79,   1,  15],
       [  2,   1,   1,   2, 135,   7],
       [  0,   0,   4,  14,   6, 267]], dtype=int64)

In [24]:
sc = accuracy_score(y_test, y_pred2)                 ## see the accuracy how it has increase

sc

0.9261849261849262

# RandomForesst & DecisionTree classification

In [25]:
from sklearn.model_selection import cross_val_score

from sklearn.tree import DecisionTreeClassifier

# Create instances of the other classification models
model1 = DecisionTreeClassifier()

scores_model1 = cross_val_score(model1, x_train, y_train, cv=5, scoring='accuracy')

print("Mean Accuracy (Model 1):", scores_model1.mean())

Mean Accuracy (Model 1): 0.8496523158500571

In [26]:
from sklearn.ensemble import RandomForestClassifier

model2 = RandomForestClassifier()

scores_model2 = cross_val_score(model2, x_train, y_train, cv=5, scoring='accuracy')

print("Mean Accuracy (Model 2):", scores_model2.mean())

Mean Accuracy (Model 2): 0.9120020379857907